server:
  port: ${SERVER_PORT_TASK5}
spring:
  datasource:
    url: ${DATABASE_URL_TASK5}
    username: ${USERNAME_TASK5}
    password: ${PASSWORD_TASK5}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    org:
      hibernate:
        sql: DEBUG


