server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hwork5
    username: postgres
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    org:
      hibernate:
        sql: DEBUG


